steam_recsys_dw:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ../data/steam.duckdb
      extensions:
        - httpfs
        - s3
      settings:
        s3_region: us-east-1
        s3_url_style: path
        s3_endpoint: localhost:9000
        s3_access_key_id: minioadmin
        s3_secret_access_key: minioadmin
        s3_use_ssl: false
