version: 2
sources:
  - name: preprocessed
    tables:
      - name: preprocessed_reviews
        config:
          external_location: '../data/preprocessed/reviews.parquet'
          format: parquet
      - name: preprocessed_users
        config:
          external_location: '../data/preprocessed/users.parquet'
          format: parquet
      - name: preprocessed_games
        config:
          external_location: '../data/preprocessed/games.parquet'
          format: parquet
