name: steam-games-rec

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../data/minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  init-minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 2;
        mc alias set localminio http://minio:9000 minioadmin minioadmin;
        mc mb localminio/raw;
        mc anonymous set public localminio/raw;
      exit 0;
      "
