name: steam-games-rec

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../data/minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"

  init-minio-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 2;
        mc alias set localminio http://minio:9000 minioadmin minioadmin;
        mc mb localminio/raw;
        mc mb localminio/clean;
        mc mb localminio/mlflow;
        mc anonymous set public localminio/raw;
        mc anonymous set public localminio/clean;
        mc anonymous set public localminio/mlflow;
      exit 0;
      "

  postgres:
    image: pgvector/pgvector:pg13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-ml:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.3.2
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      init-minio-buckets:
        condition: service_started
    environment:
      MLFLOW_S3_ENDPOINT_URL: "http://minio:9000"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
    command: >
      bash -c 'pip install psycopg2-binary boto3 && mlflow server \
                       --host 0.0.0.0 \
                       --backend-store-uri postgresql+psycopg2://postgres:postgres@postgres:5432/mlflow \
                       --artifacts-destination s3://mlflow/'

volumes:
  postgres-ml:

networks:
  default:
    name: steam-games-rec-net