FROM node:18
# Install OpenJDK
RUN apt-get update && apt-get install -y openjdk-17-jre-headless && apt-get clean
# Install Firebase CLI
RUN npm install -g firebase-tools
WORKDIR /workspace
ENTRYPOINT ["firebase", "emulators:start", "--only", "firestore", "--import=/data", "--export-on-exit=/data", "--project=steam-games-recommender"]
