[project]
name = "feature-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-duckdb>=1.9.3",
    "feast[duckdb]>=0.49.0",
]
