version: 2

models:
  - name: stg_games
    description: Contains relevant attributes for Steam Games, fetched from Steam API.
    columns:
      - name: game_id
        description: Unique ID assigned to each game in Steam.
      - name: game_name
        description: Name of the Steam game
      - name: game_is_free
        description: Whether the game is free to play or not
      - name: game_developers
        description: List of developers of the game
      - name: game_publishers
        description: List of publishers for the game. Might be different from developers
      - name: game_genres
        description: List of genres of the game
      - name: game_categories
        description: List of game categories (generally, features compatible with the game)
      - name: game_release_date
        description: Release date of the game, correctly parsed. May still be null
      - name: game_short_description
        description: Short description of the game
      - name: game_review_score
        description: General review score of a game, based on positive / negative reviews. Ranging from 0 to 10
      - name: game_review_score_description
        description: >
          Text representing the score description.
          0 -> Less than 10 reviews
          1 -> Overwhelmingly Negative
          2 -> Very Negative
          3 -> Negative
          4 -> Negative
          5 -> Mostly Negative
          6 -> Mixed
          7 -> Mostly Positive
          8 -> Positive
          9 -> Very Positive
          10 -> Overwhelmingly Positive
      - name: game_total_reviews
        description: All-time total reviews from Steam
      - name: game_total_positive_reviews
        description: All-time total positive reviews
      - name: game_total_negative_reviews
        description: All-time total negative reviews

  - name: stg_reviews
    description: Review data from all available Steam games
    columns:
      - name: review_id
        description: Unique identifier of review
      - name: user_id
        description: Anonymized user id of the reviewer
      - name: game_id
        description: Steam Game id
      - name: review
        description: Review text
      - name: timestamp_created
        description: Creation timestamp of review on UTC
      - name: written_during_early_access
        description: Whether review was written during game early access period
      - name: voted_up
        description: Whether review is positive (1) or negative (0)
      - name: weighted_vote_score
        description: Importance of review
      - name: votes_up
        description: How many votes up did the review have
      - name: comment_count
        description: Number of comments the review had
